project:
  type: website
  render:
    - "*.qmd"
    # To exclude folders you can do - "!week-09-maps/"

website:
  title: "TAD R Training"
  search:
    location: navbar
    type: overlay
  navbar:
    tools:
      - icon: github
        href:  https://github.com/DfE-R-Community/TAD-R-Training
    left:
      - href: index.qmd
        text: Home
      - href: useful-resources.qmd
        text: Useful Resources

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



